modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Tutorial Mod" #mandatory
logoFile="examplemod.png" #optional
credits="A mode developed by Bombiliu after CY4's tutorial" #optional
authors="Bombiliu" #optional
#mandatory
description='''
A tutorial mod.
'''
[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
